name: Callee

on:
  workflow_call:


jobs:
  callee:
    runs-on: ubuntu-latest
    steps:
      - name: Display env with node
        run: |
          node -e "
            Object.keys(process.env).forEach(key => {
              if (key.startsWith('ACTIONS_')) {
                console.log(\`\${key}: \${process.env[key]}\`)
              }
            })
          "