# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  show:
    runs-on: ubuntu-latest
    steps:
      # この時点では見える環境変数は1つ
      # ACTIONS_RUNNER_ACTION_ARCHIVE_CACHE=/opt/actionarchivecache 
      - name: Display env
        run: env | sort 
      - uses: actions/github-script@v6
        with:
          script: |
            keys(process.env).forEach(key => {
              if (key.startsWith("ACTIONS_")) {
                console.log(process.env[key])
              }
            })
      - name: Display env
        run: env | sort 

            
